### ISSUE TITLE
85.1 not built?

### ISSUE THREAD

**Issue by XRyu** [sqldiablo/home-assistant-docker-pymssql#1]
Hi until now it always got build when a new HA version was avaiable. But yours still is 85.0, while official is 85.1 isnt it?

**Comment by sqldiablo** [comment]
It looks like it just built 13 hours ago. Can you please give it another try and let me know if it's still on 85.0? There's quite a bit of a delay because the stock image takes over an hour to build, and then my image takes some time as well.

**Comment by sqldiablo** [comment]
Sorry for the late reply, but this seems to be resolved now. Home Assistant is tagging their container build with latest again.
