### ISSUE TITLE
No module named 'pymysql' (retrying in 3 seconds)

### ISSUE THREAD

**Issue by sylarevan** [sqldiablo/home-assistant-docker-pymssql#2]
Hello,

Don't know if I should report this here, but I've been trying to migrate my HA database to MariaDB by using your docker image, without any success. I still get the following message: 
```
Error during connection setup: No module named 'pymysql' (retrying in 3 seconds)
```

Of course, retrying to install pysmsql through 
```pip3 install --no-cache-dir pymssql``` tells me that it is already configured. So why my HA instance tells me it is not available? 
@sqldiablo, do you think there might be any missing dependencies in the docker image?

**Comment by XRyu** [comment]
Not sure you are using the right docker image, this is "pymssql", so its for MS SQL aka Microsoft SQL Server, not for MySQL / MariaDb :)

maybe you should try pymysql :)

**Comment by sylarevan** [comment]
My bad ;) Sorry for the noise!
